set_property IOSTANDARD LVDS_25 [get_ports FMC_MISO_N]
set_property IOSTANDARD LVDS_25 [get_ports FMC_MISO_P]
set_property IOSTANDARD LVDS_25 [get_ports FMC_MOSI_N]
set_property IOSTANDARD LVDS_25 [get_ports FMC_MOSI_P]
set_property IOSTANDARD LVDS_25 [get_ports FMC_CLK_N]
set_property IOSTANDARD LVDS_25 [get_ports FMC_CLK_P]
set_property PACKAGE_PIN N17 [get_ports FMC_MISO_P]
set_property PACKAGE_PIN N18 [get_ports FMC_MISO_N]
set_property PACKAGE_PIN G15 [get_ports FMC_MOSI_P]
set_property PACKAGE_PIN G16 [get_ports FMC_MOSI_N]
set_property PACKAGE_PIN J16 [get_ports FMC_CLK_P]
set_property PACKAGE_PIN J17 [get_ports FMC_CLK_N]

set_property IOSTANDARD LVCMOS25 [get_ports AUX_I2C_ENABLE]
set_property IOSTANDARD LVCMOS25 [get_ports AUX_LINK_DISABLE]
set_property PACKAGE_PIN L21 [get_ports AUX_I2C_ENABLE]
set_property PACKAGE_PIN L22 [get_ports AUX_LINK_DISABLE]

set_property IOSTANDARD LVCMOS25 [get_ports RESET_B]
set_property PACKAGE_PIN D21 [get_ports RESET_B]

set_property IOSTANDARD LVCMOS25 [get_ports FMC_LED3]
set_property IOSTANDARD LVCMOS25 [get_ports FMC_LED4]
set_property PACKAGE_PIN A21 [get_ports FMC_LED3]
set_property PACKAGE_PIN A22 [get_ports FMC_LED4]

set_property IOSTANDARD LVCMOS33 [get_ports leds]
set_property PACKAGE_PIN T22 [get_ports {leds[0]}]
set_property PACKAGE_PIN T21 [get_ports {leds[1]}]
set_property PACKAGE_PIN U22 [get_ports {leds[2]}]
set_property PACKAGE_PIN U21 [get_ports {leds[3]}]
set_property PACKAGE_PIN V22 [get_ports {leds[4]}]
set_property PACKAGE_PIN W22 [get_ports {leds[5]}]
set_property PACKAGE_PIN U19 [get_ports {leds[6]}]
set_property PACKAGE_PIN U14 [get_ports {leds[7]}]
